/**
 * generated by Xtext 2.10.0
 */
package com.anfelisa.ui;

import com.google.inject.Binder;
import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@SuppressWarnings("all")
public class AceUiModule /* implements AbstractAceUiModule  */{
  public AceUiModule(final AbstractUIPlugin plugin) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractUIPlugin) is undefined");
  }
  
  @Override
  public void configure(final Binder binder) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field super is undefined"
      + "\nconfigure cannot be resolved");
  }
}
