/**
 * generated by Xtext 2.14.0
 */
package de.acegen.ide;

import com.google.inject.Injector;
import de.acegen.AceGenStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class AceGenIdeSetup extends AceGenStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nAceGenIdeModule cannot be resolved.");
  }
}
