/**
 * generated by Xtext 2.25.0
 */
package de.acegen.aceGen.impl;

import de.acegen.aceGen.AceGenPackage;
import de.acegen.aceGen.PersistenceVerificationExpression;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Persistence Verification Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PersistenceVerificationExpressionImpl extends MinimalEObjectImpl.Container implements PersistenceVerificationExpression
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PersistenceVerificationExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AceGenPackage.Literals.PERSISTENCE_VERIFICATION_EXPRESSION;
  }

} //PersistenceVerificationExpressionImpl
