/**
 * generated by Xtext 2.21.0
 */
package de.acegen.aceGen.impl;

import de.acegen.aceGen.AceGenPackage;
import de.acegen.aceGen.PrimitiveValueDefinitionForList;
import de.acegen.aceGen.ValueDefinitionList;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Primitive Value Definition For List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.impl.PrimitiveValueDefinitionForListImpl#getValueDefinitionList <em>Value Definition List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PrimitiveValueDefinitionForListImpl extends ListAttributeDefinitionListImpl implements PrimitiveValueDefinitionForList
{
  /**
   * The cached value of the '{@link #getValueDefinitionList() <em>Value Definition List</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValueDefinitionList()
   * @generated
   * @ordered
   */
  protected EList<ValueDefinitionList> valueDefinitionList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrimitiveValueDefinitionForListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AceGenPackage.Literals.PRIMITIVE_VALUE_DEFINITION_FOR_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ValueDefinitionList> getValueDefinitionList()
  {
    if (valueDefinitionList == null)
    {
      valueDefinitionList = new EObjectContainmentEList<ValueDefinitionList>(ValueDefinitionList.class, this, AceGenPackage.PRIMITIVE_VALUE_DEFINITION_FOR_LIST__VALUE_DEFINITION_LIST);
    }
    return valueDefinitionList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AceGenPackage.PRIMITIVE_VALUE_DEFINITION_FOR_LIST__VALUE_DEFINITION_LIST:
        return ((InternalEList<?>)getValueDefinitionList()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AceGenPackage.PRIMITIVE_VALUE_DEFINITION_FOR_LIST__VALUE_DEFINITION_LIST:
        return getValueDefinitionList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AceGenPackage.PRIMITIVE_VALUE_DEFINITION_FOR_LIST__VALUE_DEFINITION_LIST:
        getValueDefinitionList().clear();
        getValueDefinitionList().addAll((Collection<? extends ValueDefinitionList>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AceGenPackage.PRIMITIVE_VALUE_DEFINITION_FOR_LIST__VALUE_DEFINITION_LIST:
        getValueDefinitionList().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AceGenPackage.PRIMITIVE_VALUE_DEFINITION_FOR_LIST__VALUE_DEFINITION_LIST:
        return valueDefinitionList != null && !valueDefinitionList.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //PrimitiveValueDefinitionForListImpl
