/**
 * generated by Xtext 2.25.0
 */
package de.acegen.aceGen.impl;

import de.acegen.aceGen.AceGenPackage;
import de.acegen.aceGen.Attribute;
import de.acegen.aceGen.PrimitiveValue;
import de.acegen.aceGen.SquishyValue;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Squishy Value</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.impl.SquishyValueImpl#getUuid <em>Uuid</em>}</li>
 *   <li>{@link de.acegen.aceGen.impl.SquishyValueImpl#getClientSystemTime <em>Client System Time</em>}</li>
 *   <li>{@link de.acegen.aceGen.impl.SquishyValueImpl#getServerSystemTime <em>Server System Time</em>}</li>
 *   <li>{@link de.acegen.aceGen.impl.SquishyValueImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link de.acegen.aceGen.impl.SquishyValueImpl#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SquishyValueImpl extends MinimalEObjectImpl.Container implements SquishyValue
{
  /**
   * The default value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected static final String UUID_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getUuid() <em>Uuid</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUuid()
   * @generated
   * @ordered
   */
  protected String uuid = UUID_EDEFAULT;

  /**
   * The default value of the '{@link #getClientSystemTime() <em>Client System Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClientSystemTime()
   * @generated
   * @ordered
   */
  protected static final String CLIENT_SYSTEM_TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getClientSystemTime() <em>Client System Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getClientSystemTime()
   * @generated
   * @ordered
   */
  protected String clientSystemTime = CLIENT_SYSTEM_TIME_EDEFAULT;

  /**
   * The default value of the '{@link #getServerSystemTime() <em>Server System Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServerSystemTime()
   * @generated
   * @ordered
   */
  protected static final String SERVER_SYSTEM_TIME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getServerSystemTime() <em>Server System Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getServerSystemTime()
   * @generated
   * @ordered
   */
  protected String serverSystemTime = SERVER_SYSTEM_TIME_EDEFAULT;

  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected Attribute attribute;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected PrimitiveValue value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SquishyValueImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AceGenPackage.Literals.SQUISHY_VALUE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getUuid()
  {
    return uuid;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setUuid(String newUuid)
  {
    String oldUuid = uuid;
    uuid = newUuid;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AceGenPackage.SQUISHY_VALUE__UUID, oldUuid, uuid));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getClientSystemTime()
  {
    return clientSystemTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setClientSystemTime(String newClientSystemTime)
  {
    String oldClientSystemTime = clientSystemTime;
    clientSystemTime = newClientSystemTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AceGenPackage.SQUISHY_VALUE__CLIENT_SYSTEM_TIME, oldClientSystemTime, clientSystemTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getServerSystemTime()
  {
    return serverSystemTime;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setServerSystemTime(String newServerSystemTime)
  {
    String oldServerSystemTime = serverSystemTime;
    serverSystemTime = newServerSystemTime;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AceGenPackage.SQUISHY_VALUE__SERVER_SYSTEM_TIME, oldServerSystemTime, serverSystemTime));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Attribute getAttribute()
  {
    if (attribute != null && attribute.eIsProxy())
    {
      InternalEObject oldAttribute = (InternalEObject)attribute;
      attribute = (Attribute)eResolveProxy(oldAttribute);
      if (attribute != oldAttribute)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, AceGenPackage.SQUISHY_VALUE__ATTRIBUTE, oldAttribute, attribute));
      }
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Attribute basicGetAttribute()
  {
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAttribute(Attribute newAttribute)
  {
    Attribute oldAttribute = attribute;
    attribute = newAttribute;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AceGenPackage.SQUISHY_VALUE__ATTRIBUTE, oldAttribute, attribute));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PrimitiveValue getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(PrimitiveValue newValue, NotificationChain msgs)
  {
    PrimitiveValue oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AceGenPackage.SQUISHY_VALUE__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(PrimitiveValue newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AceGenPackage.SQUISHY_VALUE__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AceGenPackage.SQUISHY_VALUE__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AceGenPackage.SQUISHY_VALUE__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AceGenPackage.SQUISHY_VALUE__VALUE:
        return basicSetValue(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AceGenPackage.SQUISHY_VALUE__UUID:
        return getUuid();
      case AceGenPackage.SQUISHY_VALUE__CLIENT_SYSTEM_TIME:
        return getClientSystemTime();
      case AceGenPackage.SQUISHY_VALUE__SERVER_SYSTEM_TIME:
        return getServerSystemTime();
      case AceGenPackage.SQUISHY_VALUE__ATTRIBUTE:
        if (resolve) return getAttribute();
        return basicGetAttribute();
      case AceGenPackage.SQUISHY_VALUE__VALUE:
        return getValue();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AceGenPackage.SQUISHY_VALUE__UUID:
        setUuid((String)newValue);
        return;
      case AceGenPackage.SQUISHY_VALUE__CLIENT_SYSTEM_TIME:
        setClientSystemTime((String)newValue);
        return;
      case AceGenPackage.SQUISHY_VALUE__SERVER_SYSTEM_TIME:
        setServerSystemTime((String)newValue);
        return;
      case AceGenPackage.SQUISHY_VALUE__ATTRIBUTE:
        setAttribute((Attribute)newValue);
        return;
      case AceGenPackage.SQUISHY_VALUE__VALUE:
        setValue((PrimitiveValue)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AceGenPackage.SQUISHY_VALUE__UUID:
        setUuid(UUID_EDEFAULT);
        return;
      case AceGenPackage.SQUISHY_VALUE__CLIENT_SYSTEM_TIME:
        setClientSystemTime(CLIENT_SYSTEM_TIME_EDEFAULT);
        return;
      case AceGenPackage.SQUISHY_VALUE__SERVER_SYSTEM_TIME:
        setServerSystemTime(SERVER_SYSTEM_TIME_EDEFAULT);
        return;
      case AceGenPackage.SQUISHY_VALUE__ATTRIBUTE:
        setAttribute((Attribute)null);
        return;
      case AceGenPackage.SQUISHY_VALUE__VALUE:
        setValue((PrimitiveValue)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AceGenPackage.SQUISHY_VALUE__UUID:
        return UUID_EDEFAULT == null ? uuid != null : !UUID_EDEFAULT.equals(uuid);
      case AceGenPackage.SQUISHY_VALUE__CLIENT_SYSTEM_TIME:
        return CLIENT_SYSTEM_TIME_EDEFAULT == null ? clientSystemTime != null : !CLIENT_SYSTEM_TIME_EDEFAULT.equals(clientSystemTime);
      case AceGenPackage.SQUISHY_VALUE__SERVER_SYSTEM_TIME:
        return SERVER_SYSTEM_TIME_EDEFAULT == null ? serverSystemTime != null : !SERVER_SYSTEM_TIME_EDEFAULT.equals(serverSystemTime);
      case AceGenPackage.SQUISHY_VALUE__ATTRIBUTE:
        return attribute != null;
      case AceGenPackage.SQUISHY_VALUE__VALUE:
        return value != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (uuid: ");
    result.append(uuid);
    result.append(", clientSystemTime: ");
    result.append(clientSystemTime);
    result.append(", serverSystemTime: ");
    result.append(serverSystemTime);
    result.append(')');
    return result.toString();
  }

} //SquishyValueImpl
