/**
 * generated by Xtext 2.23.0
 */
package de.acegen.aceGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Client Scenario</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.ClientScenario#getName <em>Name</em>}</li>
 *   <li>{@link de.acegen.aceGen.ClientScenario#getGivenRefs <em>Given Refs</em>}</li>
 *   <li>{@link de.acegen.aceGen.ClientScenario#getWhenBlock <em>When Block</em>}</li>
 *   <li>{@link de.acegen.aceGen.ClientScenario#getThenBlock <em>Then Block</em>}</li>
 * </ul>
 *
 * @see de.acegen.aceGen.AceGenPackage#getClientScenario()
 * @model
 * @generated
 */
public interface ClientScenario extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.acegen.aceGen.AceGenPackage#getClientScenario_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.ClientScenario#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Given Refs</b></em>' reference list.
   * The list contents are of type {@link de.acegen.aceGen.ClientScenario}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Given Refs</em>' reference list.
   * @see de.acegen.aceGen.AceGenPackage#getClientScenario_GivenRefs()
   * @model
   * @generated
   */
  EList<ClientScenario> getGivenRefs();

  /**
   * Returns the value of the '<em><b>When Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>When Block</em>' containment reference.
   * @see #setWhenBlock(ClientWhenBlock)
   * @see de.acegen.aceGen.AceGenPackage#getClientScenario_WhenBlock()
   * @model containment="true"
   * @generated
   */
  ClientWhenBlock getWhenBlock();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.ClientScenario#getWhenBlock <em>When Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>When Block</em>' containment reference.
   * @see #getWhenBlock()
   * @generated
   */
  void setWhenBlock(ClientWhenBlock value);

  /**
   * Returns the value of the '<em><b>Then Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Then Block</em>' containment reference.
   * @see #setThenBlock(ClientThenBlock)
   * @see de.acegen.aceGen.AceGenPackage#getClientScenario_ThenBlock()
   * @model containment="true"
   * @generated
   */
  ClientThenBlock getThenBlock();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.ClientScenario#getThenBlock <em>Then Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Then Block</em>' containment reference.
   * @see #getThenBlock()
   * @generated
   */
  void setThenBlock(ClientThenBlock value);

} // ClientScenario
