/**
 * generated by Xtext 2.16.0
 */
package de.acegen.aceGen;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Http Server Outcome</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.HttpServerOutcome#getName <em>Name</em>}</li>
 *   <li>{@link de.acegen.aceGen.HttpServerOutcome#getListeners <em>Listeners</em>}</li>
 *   <li>{@link de.acegen.aceGen.HttpServerOutcome#getAceOperations <em>Ace Operations</em>}</li>
 * </ul>
 *
 * @see de.acegen.aceGen.AceGenPackage#getHttpServerOutcome()
 * @model
 * @generated
 */
public interface HttpServerOutcome extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see de.acegen.aceGen.AceGenPackage#getHttpServerOutcome_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.HttpServerOutcome#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Listeners</b></em>' reference list.
   * The list contents are of type {@link de.acegen.aceGen.HttpServerViewFunction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Listeners</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Listeners</em>' reference list.
   * @see de.acegen.aceGen.AceGenPackage#getHttpServerOutcome_Listeners()
   * @model
   * @generated
   */
  EList<HttpServerViewFunction> getListeners();

  /**
   * Returns the value of the '<em><b>Ace Operations</b></em>' reference list.
   * The list contents are of type {@link de.acegen.aceGen.HttpServerAceWrite}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ace Operations</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ace Operations</em>' reference list.
   * @see de.acegen.aceGen.AceGenPackage#getHttpServerOutcome_AceOperations()
   * @model
   * @generated
   */
  EList<HttpServerAceWrite> getAceOperations();

} // HttpServerOutcome
