/**
 * generated by Xtext 2.14.0
 */
package de.acegen.aceGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Http Client State Function</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.HttpClientStateFunction#getStateFunctionType <em>State Function Type</em>}</li>
 *   <li>{@link de.acegen.aceGen.HttpClientStateFunction#getAttribute <em>Attribute</em>}</li>
 * </ul>
 *
 * @see de.acegen.aceGen.AceGenPackage#getHttpClientStateFunction()
 * @model
 * @generated
 */
public interface HttpClientStateFunction extends EObject
{
  /**
   * Returns the value of the '<em><b>State Function Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>State Function Type</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>State Function Type</em>' attribute.
   * @see #setStateFunctionType(String)
   * @see de.acegen.aceGen.AceGenPackage#getHttpClientStateFunction_StateFunctionType()
   * @model
   * @generated
   */
  String getStateFunctionType();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.HttpClientStateFunction#getStateFunctionType <em>State Function Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>State Function Type</em>' attribute.
   * @see #getStateFunctionType()
   * @generated
   */
  void setStateFunctionType(String value);

  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attribute</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(HttpClientStateElement)
   * @see de.acegen.aceGen.AceGenPackage#getHttpClientStateFunction_Attribute()
   * @model
   * @generated
   */
  HttpClientStateElement getAttribute();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.HttpClientStateFunction#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(HttpClientStateElement value);

} // HttpClientStateFunction
