/**
 * generated by Xtext 2.21.0
 */
package de.acegen.aceGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see de.acegen.aceGen.AceGenPackage#getJsonValue()
 * @model
 * @generated
 */
public interface JsonValue extends EObject
{
} // JsonValue
