/**
 * generated by Xtext 2.24.0
 */
package de.acegen.aceGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Json Member Client</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.JsonMemberClient#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link de.acegen.aceGen.JsonMemberClient#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see de.acegen.aceGen.AceGenPackage#getJsonMemberClient()
 * @model
 * @generated
 */
public interface JsonMemberClient extends EObject
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' reference.
   * @see #setAttribute(SingleClientAttribute)
   * @see de.acegen.aceGen.AceGenPackage#getJsonMemberClient_Attribute()
   * @model
   * @generated
   */
  SingleClientAttribute getAttribute();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.JsonMemberClient#getAttribute <em>Attribute</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Attribute</em>' reference.
   * @see #getAttribute()
   * @generated
   */
  void setAttribute(SingleClientAttribute value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(JsonValueClient)
   * @see de.acegen.aceGen.AceGenPackage#getJsonMemberClient_Value()
   * @model containment="true"
   * @generated
   */
  JsonValueClient getValue();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.JsonMemberClient#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(JsonValueClient value);

} // JsonMemberClient
