/**
 * generated by Xtext 2.22.0
 */
package de.acegen.aceGen;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Long Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.LongType#getLong <em>Long</em>}</li>
 * </ul>
 *
 * @see de.acegen.aceGen.AceGenPackage#getLongType()
 * @model
 * @generated
 */
public interface LongType extends JsonValueClient, JsonValue
{
  /**
   * Returns the value of the '<em><b>Long</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Long</em>' attribute.
   * @see #setLong(int)
   * @see de.acegen.aceGen.AceGenPackage#getLongType_Long()
   * @model
   * @generated
   */
  int getLong();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.LongType#getLong <em>Long</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Long</em>' attribute.
   * @see #getLong()
   * @generated
   */
  void setLong(int value);

} // LongType
