/**
 * generated by Xtext 2.25.0
 */
package de.acegen.aceGen;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Triggerd Ace Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link de.acegen.aceGen.TriggerdAceOperation#getDelay <em>Delay</em>}</li>
 *   <li>{@link de.acegen.aceGen.TriggerdAceOperation#isTakeLatest <em>Take Latest</em>}</li>
 *   <li>{@link de.acegen.aceGen.TriggerdAceOperation#getAceOperation <em>Ace Operation</em>}</li>
 * </ul>
 *
 * @see de.acegen.aceGen.AceGenPackage#getTriggerdAceOperation()
 * @model
 * @generated
 */
public interface TriggerdAceOperation extends EObject
{
  /**
   * Returns the value of the '<em><b>Delay</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Delay</em>' attribute.
   * @see #setDelay(int)
   * @see de.acegen.aceGen.AceGenPackage#getTriggerdAceOperation_Delay()
   * @model
   * @generated
   */
  int getDelay();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.TriggerdAceOperation#getDelay <em>Delay</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Delay</em>' attribute.
   * @see #getDelay()
   * @generated
   */
  void setDelay(int value);

  /**
   * Returns the value of the '<em><b>Take Latest</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Take Latest</em>' attribute.
   * @see #setTakeLatest(boolean)
   * @see de.acegen.aceGen.AceGenPackage#getTriggerdAceOperation_TakeLatest()
   * @model
   * @generated
   */
  boolean isTakeLatest();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.TriggerdAceOperation#isTakeLatest <em>Take Latest</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Take Latest</em>' attribute.
   * @see #isTakeLatest()
   * @generated
   */
  void setTakeLatest(boolean value);

  /**
   * Returns the value of the '<em><b>Ace Operation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ace Operation</em>' reference.
   * @see #setAceOperation(HttpClientAce)
   * @see de.acegen.aceGen.AceGenPackage#getTriggerdAceOperation_AceOperation()
   * @model
   * @generated
   */
  HttpClientAce getAceOperation();

  /**
   * Sets the value of the '{@link de.acegen.aceGen.TriggerdAceOperation#getAceOperation <em>Ace Operation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ace Operation</em>' reference.
   * @see #getAceOperation()
   * @generated
   */
  void setAceOperation(HttpClientAce value);

} // TriggerdAceOperation
