/**
 * generated by Xtext 2.10.0
 */
package com.anfelisa.ace;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.anfelisa.ace.Event#getName <em>Name</em>}</li>
 *   <li>{@link com.anfelisa.ace.Event#getData <em>Data</em>}</li>
 *   <li>{@link com.anfelisa.ace.Event#getListeners <em>Listeners</em>}</li>
 * </ul>
 *
 * @see com.anfelisa.ace.AcePackage#getEvent()
 * @model
 * @generated
 */
public interface Event extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.anfelisa.ace.AcePackage#getEvent_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.anfelisa.ace.Event#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Data</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Data</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' reference.
   * @see #setData(Data)
   * @see com.anfelisa.ace.AcePackage#getEvent_Data()
   * @model
   * @generated
   */
  Data getData();

  /**
   * Sets the value of the '{@link com.anfelisa.ace.Event#getData <em>Data</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data</em>' reference.
   * @see #getData()
   * @generated
   */
  void setData(Data value);

  /**
   * Returns the value of the '<em><b>Listeners</b></em>' reference list.
   * The list contents are of type {@link com.anfelisa.ace.ViewFunction}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Listeners</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Listeners</em>' reference list.
   * @see com.anfelisa.ace.AcePackage#getEvent_Listeners()
   * @model
   * @generated
   */
  EList<ViewFunction> getListeners();

} // Event
