/**
 * generated by Xtext 2.10.0
 */
package com.anfelisa.ace;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Ref</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.anfelisa.ace.ModelRef#isList <em>List</em>}</li>
 *   <li>{@link com.anfelisa.ace.ModelRef#getModel <em>Model</em>}</li>
 * </ul>
 *
 * @see com.anfelisa.ace.AcePackage#getModelRef()
 * @model
 * @generated
 */
public interface ModelRef extends EObject
{
  /**
   * Returns the value of the '<em><b>List</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>List</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>List</em>' attribute.
   * @see #setList(boolean)
   * @see com.anfelisa.ace.AcePackage#getModelRef_List()
   * @model
   * @generated
   */
  boolean isList();

  /**
   * Sets the value of the '{@link com.anfelisa.ace.ModelRef#isList <em>List</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List</em>' attribute.
   * @see #isList()
   * @generated
   */
  void setList(boolean value);

  /**
   * Returns the value of the '<em><b>Model</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model</em>' reference.
   * @see #setModel(Model)
   * @see com.anfelisa.ace.AcePackage#getModelRef_Model()
   * @model
   * @generated
   */
  Model getModel();

  /**
   * Sets the value of the '{@link com.anfelisa.ace.ModelRef#getModel <em>Model</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model</em>' reference.
   * @see #getModel()
   * @generated
   */
  void setModel(Model value);

} // ModelRef
