package de.acegen.templates.java;

import de.acegen.extensions.CommonExtension;
import javax.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class AceOperation {
  @Inject
  @Extension
  private CommonExtension _commonExtension;
  
  public CharSequence generate() {
    StringConcatenation _builder = new StringConcatenation();
    String _copyright = this._commonExtension.copyright();
    _builder.append(_copyright);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("package de.acegen;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class AceOperation {");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private ITimelineItem action;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private ITimelineItem command;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private ITimelineItem event;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("private String uuid;");
    _builder.newLine();
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public AceOperation(String uuid) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("super();");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.uuid = uuid;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ITimelineItem getAction() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return action;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ITimelineItem getCommand() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return command;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public ITimelineItem getEvent() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return event;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setAction(ITimelineItem action) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.action = action;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setCommand(ITimelineItem command) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.command = command;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public void setEvent(ITimelineItem event) {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("this.event = event;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("public String getUuid() {");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("return uuid;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    _builder.newLine();
    String _sdg = this._commonExtension.sdg();
    _builder.append(_sdg);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    return _builder;
  }
}
