/*
 * generated by Xtext 2.29.0
 */
package de.acegen.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAceGenScopeProvider extends DelegatingScopeProvider {
}
