/**
 * generated by Xtext 2.10.0
 */
package com.anfelisa.tests;

import com.google.inject.Inject;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.junit.Test;
import org.junit.runner.RunWith;

@RunWith(XtextRunner.class)/* 
@InjectWith(/* name is null */) */
@SuppressWarnings("all")
public class AceParsingTest {
  @Inject
  private /* ParseHelper<Project> */Object parseHelper;
  
  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe field AceParsingTest.parseHelper refers to the missing type Project");
  }
}
